### ISSUE TITLE
Not able to run `pre-commit` hooks

### ISSUE THREAD

**Issue by dbatten5** [lyz-code/autoimport#149]
## Description
following instructions here https://lyz-code.github.io/autoimport/contributing/#pull-requests
all steps work fine until getting to the `git commit` stage. this fails with the following error:

```
[WARNING] The 'rev' field of repo 'https://github.com/ambv/black' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[WARNING] The 'rev' field of repo 'https://github.com/life4/flakehell/' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/ambv/black.
An unexpected error has occurred: CalledProcessError: command: ('/Library/Developer/CommandLineTools/usr/libexec/git-core/git', 'checkout', 'master')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'master' did not match any file(s) known to git

Check the log at /Users/.../.cache/pre-commit/pre-commit.log
```

i believe this is due to the fact that `black` repo has no `master` branch (been renamed to `main`). however i think there are larger issues here, note the `pre-commit` warnings at the top of the trace.

also, one of the `pre-commit` hooks is [flakehell](https://github.com/life4/flakehell/) which has been archived. there is a [fork](https://github.com/flakehell/flakehell) but perhaps it would be best to use a different tool here?

## Steps to reproduce
follow the steps in the [contributing guide](https://lyz-code.github.io/autoimport/contributing/#pull-requests) and then try to commit some changes

## Current behavior
the error happens

## Desired behavior
i'm able to commit changes

## Environment

```
           autoimport version: 0.7.3
               python version: 3.7.4 (default, Sep 15 2021, 11:54:44)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
```

**Comment by lyz-code** [comment]
Hi @dbatten5 thanks again for taking the time to fill up another issue. Regarding black, yup, you're right, `master` needs to be changed to `main`. On flakehell, that repository is indeed deprecated, I've been using for a while https://github.com/flakehell/flakehell since then, but if you have any suggestions of better tools, I'm all ears :)

If you use `pre-commit autoupdate` in theory those errors are solved, but when updating [flakehell returns an error](https://github.com/flakehell/flakehell/issues/22), so until it's solved we can use an earlier version, or temporarily disable that pre-commit completely (it will be checked in the CI).
