### ISSUE TITLE
Extend `common_statements`

### ISSUE THREAD

**Issue by Jasha10** [lyz-code/autoimport#159]
## Description
I'd like to request the ability to extend the `common_statements` dict.

## Possible Solution
One idea is to allow user configuration (via e.g. `pyproject.toml` or `.autoimport.ini` or CLI arguments), so that the user can add their own common statements

## Additional context
As an example, I find myself typing `from numpy import typing as npt` quite a bit. It would be nice to automate this with autoimport.

Thanks!

**Comment by lyz-code** [comment]
Hi @Jasha10 , thank you for taking the time to open an issue.

This should be really easy to implement thanks to @dbatten5 as he already started implementing the [support to read from `pyproject.toml`](https://github.com/lyz-code/autoimport/pull/152). It's not finished because the cli is not using yet the `Config` class. He planned to do it though to solve the https://github.com/lyz-code/autoimport/issues/148 issue.

Now I've got the head elsewhere, but PRs are really welcome. If you need further guidance on how to code it, we can discuss it in this issue.

Thanks :)

**Comment by lyz-code** [comment]
I've just seen that he has created the [maison](https://dbatten5.github.io/maison) package to do exactly what we want. We could remove the code from `autoimport` and add `maison` as a requirement

**Comment by lyz-code** [comment]
It's available since `0.8.0`, super awesome contribution :)
